---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - denverton
          - geminilake
    runs-on: ubuntu-22.04
    env:
      SUFFIX: build-${{ matrix.arch }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Build
        run: date > ${{ env.SUFFIX }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SUFFIX }}
          path: ${{ env.SUFFIX }}
          if-no-files-found: error
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs: [linux]
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
      - name: Clone Repo
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Download artifacts
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} build-*
